doctrine:
  orm:
    auto_mapping: true
    mappings:
      zentlix_main_bundle:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/vendor/zentlix/main-bundle/src/Domain/Bundle/Entity'
        prefix: Zentlix\MainBundle\Domain\Bundle\Entity
      zentlix_main_datatable:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/vendor/zentlix/main-bundle/src/Domain/DataTable/Entity'
        prefix: Zentlix\MainBundle\Domain\DataTable\Entity
      zentlix_main_file:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/vendor/zentlix/main-bundle/src/Domain/File/Entity'
        prefix: Zentlix\MainBundle\Domain\File\Entity
      zentlix_main_locale:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/vendor/zentlix/main-bundle/src/Domain/Locale/Entity'
        prefix: Zentlix\MainBundle\Domain\Locale\Entity
      zentlix_main_setting:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/vendor/zentlix/main-bundle/src/Domain/Setting/Entity'
        prefix: Zentlix\MainBundle\Domain\Setting\Entity
      zentlix_main_site:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/vendor/zentlix/main-bundle/src/Domain/Site/Entity'
        prefix: Zentlix\MainBundle\Domain\Site\Entity
  dbal:
    types:
      meta: Zentlix\MainBundle\Infrastructure\Share\Doctrine\MetaType
      uuid_binary: Ramsey\Uuid\Doctrine\UuidBinaryType
    mapping_types:
      uuid_binary: binary